version: "3"

services:
  postgres:
    image: postgres:11
    container_name: mostly-tracker-db
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mostly-tracker
      - POSTGRES_USER=tracker
      - POSTGRES_PASSWORD=tracker
    networks:
      - mostly-tracker

networks:
  mostly-tracker:
